//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int iddoc { get; set; }
        public string tipodoc { get; set; }
        public string coddoc { get; set; }
        public string cedulaempleado { get; set; }
        public string fechacreacion { get; set; }
        public string departamentoorigen { get; set; }
        public string departamentodestino { get; set; }
    }
}
