//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidades;

    public partial class ControlDocumentosEntities : DbContext
    {
        public ControlDocumentosEntities()
            : base("name=ControlDocumentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<date_range_Result> date_range(string fechaini, string fechafi)
        {
            var fechainiParameter = fechaini != null ?
                new ObjectParameter("fechaini", fechaini) :
                new ObjectParameter("fechaini", typeof(string));
    
            var fechafiParameter = fechafi != null ?
                new ObjectParameter("fechafi", fechafi) :
                new ObjectParameter("fechafi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<date_range_Result>("date_range", fechainiParameter, fechafiParameter);
        }
    }
}
